version: '3.8'
services:
  api:
    environment:
      FLASK_ENV: development
      MONGO_HOST: mongo
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   environment:  
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  # frontend:
  #   # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
  #   stdin_open: true
  #   ports:
  #     - 3000:3000
  #   command: npm start
