version: '3.8'
services:
  api:
    environment:
      FLASK_ENV: production
    depends_on: frontend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/frontend:/code
    command: npm run build
