version: '3.8'
services:
  api:
    environment:
      FLASK_ENV: development
      FLASK_TESTING: "True"
      MONGO_DATABASE: example_test
    command: ./app/test.sh
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8000:8081
    environment:  
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
