version: '3.8'
services:
  api:
    environment:
      FLASK_ENV: production
      MONGO_HOST: mongo
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    depends_on: frontend
  frontend:
    command: npm run build
