version: '3.8'
services:
  api:
    build: ./app
    volumes:
      - $VOLUME_PATH:/code
    environment:
      FLASK_APP: ./app/backend/server.py
      FLASK_RUN_HOST: 0.0.0.0
      MONGO_HOST: $MONGO_HOST
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
    command: ./app/run.sh
