version: '3.8'
services:
  api:
    environment:
      FLASK_ENV: development
      MONGO_DATABASE: example_dev
    depends_on:
      - mongo
    ports:
      - "3002:5000"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3003:8081
    environment:  
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
  frontend:
    build: ./frontend
    volumes:
      - $VOLUME_PATH/frontend/frontend:/code
    # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    stdin_open: true
    ports:
      - 3004:3000
    command: bash -c "npm install && npm start"