version: '3.8'
services:
  api:
    environment:
      FLASK_ENV: production
      MONGO_DATABASE: example_prod
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/frontend:/code
    command: npm run build
