version: '3.8'
services:
  api:
    environment:
      FLASK_ENV: production
      MONGO_DATABASE: example_prod
    depends_on:
      - frontend
    ports:
      - "3005:5000"
  frontend:
    build: ./frontend
    volumes:
      - $VOLUME_PATH./frontend/frontend:/code
    command: bash -c "npm install && npm run build"
