version: '3.8'
services:
  api:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_APP: ./app/app/server.py
      FLASK_RUN_HOST: 0.0.0.0
    command: flask run
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/frontend:/code
