version: '3.8'
services:
  api:
    environment:
      FLASK_ENV: development
      MONGO_DATABASE: example_dev
    depends_on:
      - mongo-seed
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8000:8081
    environment:  
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
  mongo-seed:
    build: ./app
    volumes:
      - .:/code
    environment:
      MONGO_HOST: $MONGO_HOST
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DATABASE: example_dev
    command: ./app/seed.sh
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/frontend:/code
    # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    stdin_open: true
    ports:
      - 3000:3000
    command: npm start